### ISSUE TITLE
Mobile App crashes android

### ISSUE THREAD

**Issue by killmasta93** [linagora/Twake-Mobile#1467]
Hi Currently installed Twake on docker 
version: "3.4"
```

services:
  mongo:
    container_name: mongo
    image: mongo:4.4.6
    volumes:
      - ./docker-data/mongo:/data/db

  node:
    image: twaketech/twake-node:latest
    ports:
      - 3000:3000
      - 8083:3000
    environment:
      - DEV=production
      - SEARCH_DRIVER=mongodb
      - DB_DRIVER=mongodb
      - PUBSUB_TYPE=local
    volumes:
      - ./configuration/backend-node/production.json:/usr/src/app/config/production.json
      - ./docker-data/documents/:/storage/
    depends_on:
      - mongo
    links:
      - mongo
```

and works on the web login and app login on the computer, but on mobile android when i change the server and try to login it keeps crashing
not sure if i need to install something else?

Thank yo u
